<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Contact;
use App\Models\Property;
use Faker\Generator as Faker;

$factory->define(Property::class, function (Faker $faker) {
    return [
        'owner_id' => Contact::all()->random()->id,
        'contact_id' => Contact::all()->random()->id,
        'name' => $faker->lexify('Property ???'),
        'sale_price_asking' => $faker->numberBetween(1, 1000),
        'sale_price_asking_date' => now(),
        'sale_price_asking_date_by' => $faker->name,
        'sale_price' => $faker->numberBetween(1, 1000),
        'sale_price_date' => now(),
        'sale_price_updated_by' => $faker->name,
        'sale_list_price' => $faker->numberBetween(1, 1000),
        'sale_list_price_date' => now(),
        'sale_list_price_updated_by' => $faker->name,
        'sold_price' => $faker->numberBetween(1, 1000),
        'sold_price_date' => now(),
        'sold_price_updated_by' => $faker->name,
        'rent_price_asking' => $faker->numberBetween(1, 1000),
        'rent_price_asking_date' => now(),
        'rent_price_asking_updated_by' => $faker->name,
        'rent_price' => $faker->numberBetween(1, 1000),
        'rent_price_date' => now(),
        'rent_price_updated_by' => $faker->name,
        'rent_list_price' => $faker->numberBetween(1, 1000),
        'rent_list_date' => now(),
        'rent_list_price_updated_by' => $faker->name,
        'rented_price' => $faker->numberBetween(1, 1000),
        'rented_price_date' => now(),
        'rented_price_update_by' => $faker->name,
        'zip_postalcode' => $faker->postcode,
        'latitude' => $faker->latitude($min = -90, $max = 90) ,
        'longitude' => $faker->longitude($min = -180, $max = 180),
        'published_at' => now(),
        'published_by' => $faker->name,
        // 'unit_total_bathroom' => $faker->numberBetween(1, 1000),
        // 'unit_total_bedroom' => $faker->numberBetween(1, 1000),
        // 'unit_total_livingroom' => $faker->numberBetween(1, 1000),
        // 'unit_total_floor' => $faker->numberBetween(1, 1000),
        // 'unit_total_parking' => $faker->numberBetween(1, 1000),
        // 'unit_total_car_parking' => $faker->numberBetween(1, 1000),
        // 'unit_total_motor_parking' => $faker->numberBetween(1, 1000),
        // 'unit_total_diningroom' => $faker->numberBetween(1, 1000),
        // 'unit_total_doors' => $faker->numberBetween(1, 1000),
        // 'land_area_by_title_deed' => $faker->numberBetween(1, 1000),
        // 'note' => $faker->paragraphs(4),
        // 'location_grade' => $faker->,
        'label_type' => $faker->randomElement($array = array ('New','Second Hand')),
        'building_width' => $faker->numberBetween(1, 1000),
        'building_length' => $faker->numberBetween(1, 1000),
        'building_height' => $faker->numberBetween(1, 1000),
        'building_area' => $faker->numberBetween(1, 1000),
        'photo_front_side' => $faker->imageUrl($width = 640, $height = 480),
        'photo_left_side' => $faker->imageUrl($width = 640, $height = 480),
        'photo_right_side' => $faker->imageUrl($width = 640, $height = 480),
        'photo_back_side' => $faker->imageUrl($width = 640, $height = 480),
        'photo_opposite' => $faker->imageUrl($width = 640, $height = 480),
        'images' => $faker->imageUrl($width = 640, $height = 480),
        // Address
        'street_no' => $faker->streetAddress,
        'house_no' => $faker->buildingNumber,
        'province' => $faker->word,
        'district' => $faker->word,
        'commune' => $faker->word,
        'village' => $faker->word,
        'address' => $faker->address,
        // Property Basic Information
        'record_type' => $faker->randomElement($array = array ('Land','Building')),
        'tenure_type' => $faker->randomElement($array = array ('Freehold','LeaseHold')),
        'type' => $faker->randomElement($array = array ('Vacant_Land','Agrultural Property','Apartment','Condominum','Commercial Property','Industrial Property','Residential Property','Specialized Property','Mixed-user')),
        'zone_type' => $faker->randomElement($array = array ('Residential','Industrial','Residential/Commercial','Agricultural','Agricultural/Residential')),
        'current_use' => $faker->randomElement($array = array ('Vacant_Land','Agrultural Property','Apartment','Condominum','Commercial Property','Industrial Property','Residential Property','Specialized Property','Mixed-user')),
        'view' => $faker->randomElement($array = array ('North','East','West','South')),
        'data_source' => $faker->randomElement($array = array ('Owner','Agent','Brokery','Buyer')),
        'topography' => $faker->randomElement($array = array ('Level','Unlevelled','Unfilled')),
        'land_width' => $faker->numberBetween(1, 1000),
        'land_shape_type' => $faker->randomElement($array = array ('Rectangle','Square','L-Shape','Triangle','Irregular')),
        'land_area' => $faker->numberBetween(1, 1000),
        'land_length' => $faker->numberBetween(1, 1000),
        'project_building' => $faker->randomElement($array = array ('Borey Peng Hout','Borey Leng Navatra')),
        //Title Deed Information
        'title_deed_type' => $faker->randomElement($array = array ('Hard (LMAP)','Hard (Sporadic Registration)','Letter of Possession Transfer','Strata Title','Sale and Purchase Agreement','Long-Term Lease','Soft Title (unspecified)','Hard Title (unspecified)')),
        'title_deed_no' => $faker->numberBetween(1, 1000),
        'issued_year' => $faker->numberBetween(1, 1000),
        'parcel_no' => $faker->numberBetween(1, 1000),
        'title_deed_photos' => $faker->imageUrl($width = 640, $height = 480),
       // Property Information
       'is_rent' => $faker->boolean,
       'is_sale' => $faker->boolean,
       'description' => $faker->paragraph,

        // 'stories' => $faker->numberBetween(1, 1000),
        // 'shape' => $faker->,
        // 'functional_utilities' => $faker-> ,
        // 'main_street' => $faker->address,
        // 'property_code' => $faker->numberBetween(1, 1000),
        // 'code' => $faker->numberBetween(1, 1000),
        'created_by' => $faker->name,
        'updated_by' => $faker->name,
        'created_at' => now(),
        'updated_at' => now(),
        'deleted_at' => now(),
    ];
});
